### ISSUE TITLE
xUnit test cases do not run on Windows

### ISSUE THREAD

**Issue by lextm** [xunit/xamarinstudio.xunit#25]
After fixing #22 the test cases can be discovered and displayed on the panel.

However, execution of them leads to .NET remoting related exceptions so no result can be collected.

**Comment by lextm** [comment]
The new exception is as below,

```
System.Runtime.Serialization.SerializationException: Unable to find assembly 'MonoDevelop.XUnit, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo(BinaryTypeEnum binaryTypeEnum, Object typeInformation, ObjectReader objectReader, BinaryAssemblyInfo assemblyInfo, InternalPrimitiveTypeE& primitiveTypeEnum, String& typeString, Type& type, Boolean& isVariant)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MonoDevelop.XUnit.XUnitTestRunner.Execute(String assembly, XUnitTestInfo[] testInfos, IXUnitExecutionListener executionListener)
   at MonoDevelop.XUnit.XUnitTestExecutor.Run(List`1 testCases, XUnitAssemblyTestSuite rootSuite, IExecutableTest test, TestContext context, Boolean reportToMonitor) in C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\XUnitTestExecutor.cs:line 129
```

WinDbg shows that the remoting process was trying to deserialize XUnitTestInfo objects from add-in, but failed to do so as it could not find the assembly. 

However, `!DumpDomain` shows the assembly has been loaded to Domain 1. So not sure what's up on .NET remoting yet.

**Comment by lextm** [comment]
Before this issue is resolved, since Visual Studio has xUnit.net support, you can use Visual Studio as a workaround.

We might get rid of .NET remoting, which should then resolve this issue too. But that's going to take much more time.

**Comment by lextm** [comment]
After using JSON.NET to serialize XUnitTestInfo objects (instead of relying on .NET remoting's own), that exception is resolved.

The latest exception is,

```
System.Runtime.Remoting.RemotingException: The argument type 'System.MarshalByRefObject' cannot be converted into parameter type 'MonoDevelop.XUnit.IXUnitExecutionListener'. ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   at System.Runtime.Remoting.Messaging.Message.CoerceArgs(MethodBase mb, Object[] args, ParameterInfo[] pi)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MonoDevelop.XUnit.XUnitTestRunner.Execute(String assembly, String data, IXUnitExecutionListener executionListener)
   at MonoDevelop.XUnit.XUnitTestExecutor.Run(List`1 testCases, XUnitAssemblyTestSuite rootSuite, IExecutableTest test, TestContext context, Boolean reportToMonitor) in C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\XUnitTestExecutor.cs:line 127
```

Still it seems to be a .NET remoting issue.

**Comment by autonomy-rocks** [comment]
Might be relevant.

http://spazzarama.com/2009/06/25/binary-deserialize-unable-to-find-assembly/

**Comment by autonomy-rocks** [comment]
For easier debugging, you can also do something like the following. It will output the exceptions to the Application Output window when debugging the add-in.

```
using (var runner = (XUnitTestRunner)Runtime.ProcessService.CreateExternalProcessObject(typeof(XUnitTestRunner), context.ExecutionContext.ExecutionHandler, rootSuite.SupportAssemblies))
{
    try
    {
        runner.Execute(rootSuite.AssemblyPath, testCases.Select(tc => tc.TestInfo).ToArray(), executionListener);
    }
    catch (Exception ex)
    {
        LoggingService.LogError("", ex);
    }
}
```

**Comment by lextm** [comment]
I already did that. Thanks.

Created #26 to track the progress on migrating away from .NET remoting.

**Comment by lextm** [comment]
Tested after merging #31. Now it runs on Windows without any issue. Will publish a new build to add-in repo once we solve other remaining issues.
